name: cuda121
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - defaults
  - nvidia/label/cuda-12.1.1
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.44=h9d8b0ac_4
  - binutils_linux-64=2.44=h4852527_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cmake=4.1.2=hc85cc9f_0
  - cuda-cccl=12.1.109=0
  - cuda-command-line-tools=12.1.1=0
  - cuda-compiler=12.1.1=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-static=12.1.105=0
  - cuda-cuobjdump=12.1.111=0
  - cuda-cupti=12.1.105=0
  - cuda-cupti-static=12.1.105=0
  - cuda-cuxxfilt=12.1.105=0
  - cuda-documentation=12.1.105=0
  - cuda-driver-dev=12.1.105=0
  - cuda-gdb=12.1.105=0
  - cuda-libraries=12.1.1=0
  - cuda-libraries-dev=12.1.1=0
  - cuda-libraries-static=12.1.1=0
  - cuda-nsight=12.1.105=0
  - cuda-nsight-compute=12.1.1=0
  - cuda-nvcc=12.1.105=0
  - cuda-nvdisasm=12.1.105=0
  - cuda-nvml-dev=12.1.105=0
  - cuda-nvprof=12.1.105=0
  - cuda-nvprune=12.1.105=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvrtc-static=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvp=12.1.105=0
  - cuda-opencl=12.1.105=0
  - cuda-opencl-dev=12.1.105=0
  - cuda-profiler-api=12.1.105=0
  - cuda-sanitizer-api=12.1.105=0
  - cuda-toolkit=12.1.1=0
  - cuda-tools=12.1.1=0
  - cuda-version=12.1=h1f5ad73_3
  - cuda-visual-tools=12.1.1=0
  - gcc_impl_linux-64=12.4.0=h26ba24d_2
  - gcc_linux-64=12.4.0=h6b7512a_10
  - gds-tools=1.6.1.9=0
  - gxx_impl_linux-64=12.4.0=h3ff227c_2
  - gxx_linux-64=12.4.0=h8489865_10
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libcublas=12.1.3.1=0
  - libcublas-dev=12.1.3.1=0
  - libcublas-static=12.1.3.1=0
  - libcufft=11.0.2.54=0
  - libcufft-dev=11.0.2.54=0
  - libcufft-static=11.0.2.54=0
  - libcufile=1.6.1.9=0
  - libcufile-dev=1.6.1.9=0
  - libcufile-static=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcurand-static=10.3.2.106=0
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.4.5.107=0
  - libcusolver-dev=11.4.5.107=0
  - libcusolver-static=11.4.5.107=0
  - libcusparse=12.1.0.106=0
  - libcusparse-dev=12.1.0.106=0
  - libcusparse-static=12.1.0.106=0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=12.4.0=h1762d19_102
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.1.0.40=0
  - libnpp-dev=12.1.0.40=0
  - libnpp-static=12.1.0.40=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.2.0.2=0
  - libnvjpeg-dev=12.2.0.2=0
  - libnvjpeg-static=12.2.0.2=0
  - libnvvm-samples=12.1.105=0
  - libsanitizer=12.4.0=ha732cd4_2
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=12.4.0=h1762d19_102
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - ninja=1.13.1=h171cf75_0
  - nsight-compute=2023.1.1.4=0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - rhash=1.4.6=hb9d3cd8_1
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2025.11.12
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - filelock==3.19.1
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - openai==2.9.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - plyfile==1.1.3
      - psutil==7.1.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
